framework:
  messenger:
    failure_transport: failed

    transports:
      async: "sync://"
      failed: "doctrine://default?queue_name=failed"
      sync: "sync://"

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      # 或者直接使用同步传输
      # Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
